version: '3'

services:
  researcheye-graphql:
    image: researcheye.backend.service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 5000:5000
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - RESEARCHEYE_HOST=${RESEARCHEYE_HOST}
      - RESEARCHEYE_PORT=${RESEARCHEYE_PORT}
      - RESEARCHEYE_DB=${RESEARCHEYE_DB}
      - RESEARCHEYE_USR=${RESEARCHEYE_USR}
      - RESEARCHEYE_PWD=${RESEARCHEYE_PWD}
      - AUTH_TOKEN=${AUTH_TOKEN}
